openapi: 3.0.1
info:
  title: rh-react-micro-template
  x-cortex-git:
    github:
      repository: RHCommerceDev/rh-react-micro-template
  x-cortex-tag: rh-react-micro-template
  x-cortex-dashboards:
    embeds:
      - url: https://grafana.rhapsody.rh.com/d-solo/KOgZsyJik/generic-service-dashboard?orgId=1&from=now-24h&to=now&refresh=30s&var-namespace=production&var-service=rh-react-micro-template-v1&panelId=4
        type: grafana
      - url: https://grafana.rhapsody.rh.com/d-solo/KOgZsyJik/generic-service-dashboard?orgId=1&from=now-24h&to=now&refresh=30s&var-namespace=production&var-service=rh-react-micro-template-v1&panelId=11
        type: grafana
  x-cortex-static-analysis:
    sonarqube:
      project: org.rh:rh-react-micro-template
  x-cortex-service-groups:
    - domain/ecommerce
